### ISSUE TITLE
unable to start server with univcorn 

### ISSUE THREAD

**Issue by VallariAg** [ceph/teuthology-api#35]
when starting server with uvicorn, it's unable to start server:

```bash
$ uvicorn main:app --reload --port 8083 --host 0.0.0.0
INFO:     Will watch for changes in these directories: ['/Users/vallari/Documents/work/teuthology-api']
INFO:     Uvicorn running on http://0.0.0.0:8083 (Press CTRL+C to quit)
INFO:     Started reloader process [17237] using WatchFiles
ERROR:    Error loading ASGI app. Could not import module "main".
```

Note: docker setup starts uvicorn server when `DEPLOYMENT=development`

**Comment by Devansh3712** [comment]
I think I went through a similar problem, rather than running the command in the `src/teuthology_api` directory, run `uvicorn src.teuthology_api.main:app --reload` which might fix this issue.

**Comment by VallariAg** [comment]
using `teuthology_api.main:app` fixed this!
