### ISSUE TITLE
Dependency: Should not use different teuthology branch

### ISSUE THREAD

**Issue by zmc** [ceph/teuthology-api#9]
```
zack@teuthology:~/teuthology-api$ grep teuthology requirements.txt
# Temporarily, using teuthology without monkey patching the thread
git+https://github.com/VallariAg/teuthology@teuth-api#egg=teuthology[test]
# Original: git+https://github.com/ceph/teuthology#egg=teuthology[test]
```

I didn't see a separate issue dedicated to this.

**Comment by zmc** [comment]
The change to use a branch in the ceph org's repo is positive, but doesn't quite resolve this. It may be the case that we could stop monkey patching threads in teuthology main, but we'd want to test that - otherwise, perhaps there's another way to make this work.

**Comment by VallariAg** [comment]
We are using teuthology main branch now: https://github.com/ceph/teuthology-api/pull/49
